### ISSUE TITLE
Event for when moving the chart and resizing the chart

### ISSUE THREAD

**Issue by NTass02** [Cainier/draggable-panel#2]
Is there an event for when the chart object gets moved or resized? I need to capture those two things so I can save the size of the chart.

**Comment by Cainier** [comment]
Ok, I will add the events chart-move and chart-scale in the next version

NTass02 ***@***.***> 于2022年10月31日周一 21:47写道：

**Comment by Cainier** [comment]
Events chart-move / chart-scale is added in v1.0.10

**Comment by ayonbhattacharya** [comment]
@NTass02  How are you saving the size of the chart please?

**Comment by NTass02** [comment]
> @NTass02 How are you saving the size of the chart please?

I am storing the width and height and x and y coordinates.
